### ISSUE TITLE
Catalog-of-my-things-ruby-Captsone

### ISSUE THREAD

**Issue by Haywayaheadshot** [Haywayaheadshot/catalog-of-my-things#16]
_This is the Ruby Capstone Project we are going to work with 3 members and we are assigned by:_
`#Team member 1` : @Haywayaheadshot 
`#Team member 2` :@Goruchie
`#Team member 3` : @StarMindz

https://github.com/users/Haywayaheadshot/projects/7

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Please make sure to assign all tasks to team members so that eventually all tasks are assigned equally (with respect to points for each task) between all team members, as per [this](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#:~:text=Each%20of%20the,should%20have%20assignees.) requirement.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GzimAsani** [comment]
### Hello team                          :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job assigning tasks, but please do for all of them :+1: 

 ## Required Changes 

- [ ] As asked by the previous reviewer please assign all tasks to team members, do not leave a task unassigned. Also please make sure that tasks are fairly distributed.
Unassigned tasks:
![image](https://user-images.githubusercontent.com/62705947/212724619-ee197603-2f45-4dca-b8f6-f1bf8dd0d64d.png)
![image](https://user-images.githubusercontent.com/62705947/212724660-546ee21a-09da-4610-bbc2-279ac936101f.png)




 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@GzimAsani Thank you for reviewing our project but the requirement says if we are 3 members, we should ignore the fourth requirement

**Comment by Haywayaheadshot** [comment]
@GzimAsani I have closed the tasks for a fourth member since we do not have one.

**Comment by GzimAsani** [comment]
> @GzimAsani I have closed the tasks for a fourth member since we do not have one.

Hi there, sorry for the confusion caused, but yes the requirement is that every task should be assigned to a team member. You did a good job removing the tasks which are for the fourth team member

**Comment by Haywayaheadshot** [comment]
Thank you @GzimAsani. I have submitted it again.

**Comment by Munsa1** [comment]
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@Munsa1 Thank you for reviewing our project.
